import type { Metadata } from 'next'
import React from 'react'
import Script from 'next/script'
import './globals.css'
import StyledComponentsRegistry from '@/library/antd/styledComponentsRegistry'
import Provider from '@/provider/provider'

export const metadata: Metadata = {
  title: 'Next js 14, POCKY',
  description: 'Generated by doremi',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY}&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive"
        />
        <StyledComponentsRegistry>
          <Provider>{children}</Provider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
