server:
  port: 32100
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    additional-tld-skip-patterns: "*.jar"
spring:
   thymeleaf:
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      cache: false #default true, dev mode false
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: ${SPRING_MYSQL_URL}
     username: ${SPRING_MYSQL_USERNAME}
     password: ${SPRING_MYSQL_PASSWORD}
   hikari:
     connection-timeout: 20000
     validation-timeout: 3000
     minimum-idle: 5
     maximum-pool-size: 12
     idle-timeout: 300000
     max-lifetime: 1200000
     auto-commit: true
     pool-name: mysqlPool
   servlet:
     multipart:
     enabled: true
mybatis:
  # Mapper locations
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #location: classpath:mybatis-config.xml
# JPA Configuration (ensure this is properly integrated with your Spring Boot JPA setup)
jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: ${SPRING_KAKAO_RESTAPI_KEY} # KAKAO REST API KEY
          redirect-uri: ${SPRING_KAKAO_REDIRECT_URI} # Next JS Redirect URI
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          client-name: Kakao
          scope:
            - profile_nickname
            - account_email
        naver:
          client-id:
          client-secret:
          redirect-uri: http://localhost:3000/oauth/callback/naver
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
